version: "3"
services:
  db:
    image: postgres:10.13
    environment:
      POSTGRES_PASSWORD: limor567
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 2435:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    privileged: true
